site_name: FRC Learn
repo_name: Galaxia5987/frc-learn
repo_url: https://github.com/Galaxia5987/frc-learn
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  palette:
    scheme: slate
  icon:
    edit: fontawesome/solid/pen
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.footer
    - content.code.copy
    - navigation.expand
    - content.tabs.link
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      auto_title: true
      use_pygments: true
      anchor_linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.details
  - admonition
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-committers:
      enabled: !ENV [GITHUB_CD, false]
      repository: Galaxia5987/frc-learn
      branch: main

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: GTM-T23HXV6D
